version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "1323:1323"
    links:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27018:27017'
    volumes:
      - ./data:/data/db